<?php
/**
 * @name         :  Apptha One Step Checkout
 * @version      :  1.1
 * @since        :  Magento 1.4
 * @author       :  Apptha - http://www.apptha.com
 * @copyright    :  Copyright (C) 2011 Powered by Apptha
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  June 20 2011
 * 
 * */
echo $this->settings['enable_comments'];
?>

 <?php if($this->settings['enable_comments']): ?>
            <div class="onestepcheckout-comments">
                <label for="id_comments"><?php echo $this->__('Comments'); ?></label><br/>
                <textarea id="id_comments" name="onestepcheckout_comments"><?php if(isset($_POST['onestepcheckout_comments'])) { echo $_POST['onestepcheckout_comments']; } ?></textarea>
            </div>
<?php endif; ?>