<table cellspacing="0" class="data-table" id="checkout-review-table">
    <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
    <thead>
        <tr>
            <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
            <th class="a-center" rowspan="<?php echo $rowspan ?>" width="5%"><?php echo $this->__('Qty') ?></th>
            <th class="a-center" colspan="<?php echo $colspan ?>" width="10%"><?php echo $this->__('Subtotal') ?></th>
        </tr>
        <?php //if ($this->helper('tax')->displayCartBothPrices()):?>
        <!--<tr>
            <th class="a-center"><?php //echo $this->__('Excl. Tax'); ?></th>
            <th class="a-center"><?php //echo $this->__('Incl. Tax'); ?></th>
            <th class="a-center"><?php //echo $this->__('Excl. Tax'); ?></th>
            <th class="a-center"><?php //echo $this->__('Incl. Tax'); ?></th>
        </tr>-->
        <?php //endif; ?>
    </thead>
    <tbody>
        <?php foreach($this->getItems() as $_item):?>
        <tr>
            <td class="attributes-col"><?php echo $_item->getName() ?></td>
            <td class="a-center"><?php echo $_item->getQty() ?></td>
            <td class="a-right"><?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
    <?php
    $totals = $this->getTotals();
    if ($this->getTotals()): ?>
    <tfoot>
        <?php foreach($totals as $total): ?>
        <tr>
            <td colspan="2"><?php echo $total->getTitle()?></td>
            <td><?php echo $this->helper('checkout')->formatPrice($total->getValue())?></td>
        </tr>
        <?php endforeach;?>
    </tfoot>
    <?php endif; ?>
</table>
<script type="text/javascript">
    //<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
    //]]>
</script>
