<?php
/**
 * @ Author     : Apptha team
 * @package     : Apptha_Airhotels
 * @copyright   : Copyright (c) 2011 (www.apptha.com)
 * @license     : http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Modified Date:June 2012
 */
?>
<?php
/**
 * Host Property list page 
 * 
 *  @see Apptha_airhotels_Block_Property_Yourlist
 */
?>
<?php
//Loggin Customer details
$customer = Mage::getSingleton('customer/session')->getCustomer();
$cus_id = $customer->getId();
$cus_name = $customer->getName();
?>
<div id="rooms">
    <div id="room" class="clearfix">
        <div id="left_column">
            <div id="main_content" class="box">
                <div class="middle">
                    <ul id="main_content_sub_nav" class="rooms_sub_nav clearfix">
                        <li id="manageListing"
                            onclick="select_tab(&#39;main&#39;, &#39;list_div&#39;, jQuery(this)); initPhotoGallery();"
                            class="main_link selected"><a href="#"><?php echo $this->__('Manage Listing'); ?></a></li>
                        <li id="bookingHistory"onclick="select_tab(&#39;main&#39;, &#39;reserve_div&#39;, jQuery(this)); load_map_wrapper(&#39;load_google_map&#39;);"
                            class="main_link"><a href="#"><?php echo $this->__('Booking History') ?></a>

                        </li>
                        <li id="content_flag"></li>
                    </ul>
                    <!-- Property List Start-->
                    <div id="list_div" class="main_content"
<?php
if ($this->getRequest()->getParam('from') || $this->getRequest()->getParam('clear'))
    echo " style='display:none' "; else
    echo " style='display:block' "
    ?>
                         style="display: block;">


                        <div class="fieldset floatleft" id="manage_list">
                            <div class="yourlist_main"><?php
                $model = Mage::getModel('catalog/product');
                $todayDate = strtotime(Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT));
                $todayDate = date('m/d/y', $todayDate);
                $products = Mage::getModel('airhotels/property')->getpropertycollection()
                        ->addFieldToFilter(array(
                            array('attribute' => 'Userid', 'eq' => $cus_id),));
                if (count($products) >= 1) {
                    
                   $c = 0;
                    foreach ($products as $_product) {
                        //print_r($_product);
                       $baseurl = Mage::getBaseUrl('media');
                       
                       
        ?>                <?php
                                $yourlist=$this->helper('catalog/image')->init($_product, 'image')
                                ->constrainOnly(TRUE)
                                ->keepAspectRatio(TRUE)
                                ->keepFrame(FALSE)
                                ->resize(63,null)
                            ?>                
                                        <div class="listing_main">
                                            
                                            <div class="yourlist_img"><?php if ($_product->getImage()) { ?> <img
                                                        src="<?php echo $yourlist; ?>"
                                                        style="width: 63px !important; height: 53px !important"> <?php } else { ?>
                                                    <img
                                                        src="<?php echo $this->getSkinUrl('images/np_more_img.gif'); ?>"
                                                        style="width: 63px !important; height: 53px !important"> <?php } ?>
                                                    <div class="listing-info">
                                                        <div class="clearfix">
                                                    <span><?php echo $_product->getName(); ?></span>
                                                    <div class="slider-widget-container">
                                                        <ul>
                                                              <li id="active<?php echo $c; ?>"
                                                        <?php echo ($_product->getStatus() == 2) ? "style='display:block'" : "style='display:none'"; ?>><a

                                                            title="Active" class="yourlist_imgbtn visible_grid" id="active"
                                                            name="active"
                                                            onClick="airbnbActivate('1','<?php echo $c; ?>','active<?php echo $c; ?>')" ></a></li>
                                                    <li id="hide<?php echo $c; ?>"
                                                        <?php echo ($_product->getStatus() == 1) ? "style='display:block'" : "style='display:none'"; ?>><a
                                                           
                                                           title="Deactive" class="yourlist_imgbtn hide_grid" id="deactive"
                                                            name="active"
                                                            onClick="airbnbActivate('2','<?php echo $c; ?>','hide<?php echo $c; ?>')" ></a>
                                                        <input type="hidden" id="productId<?php echo $c; ?>"
                                                               value="<?php echo $_product->getId(); ?>" /></li>
                                                    <li id="loadingSpace<?php echo $c; ?>"></li>
                                                        </ul>
                                                    </div>
                                                    </div>
                                                    <div class="actions_grid">
                                                        <strong class="action_button" id="preview">
                                                            <a class="icon_list preview_grid" title="Preview"  
                                                               onClick="location.href='<?php echo $_product->getProductUrl(); ?>'"  
                                                               target="_blank" ><?php echo $this->__('Preview') ?></a>
                                                        </strong>
                                                        <strong class="action_button">
                                                            <a class="icon_list edit" title="Edit" target="_blank" 
                                                               onClick="location.href='<?php echo Mage::helper('airhotels')->getediturl(); ?>id/<?php echo $_product->getId(); ?>'">
                                                               <?php echo $this->__('Edit') ?></a>
                                                        </strong>
                                                        <strong class="action_button">
                                                            <a class="icon_list calender" target="_blank" title="Calender"  
                                                               onClick="location.href='<?php echo Mage::getBaseUrl() . "airhotels/property/blockcalendar/"; ?>id/<?php echo $_product->getId(); ?>'">
                                                               <?php echo $this->__('Calender') ?></a>
                                                        </strong>
                                                         <strong class="action_button">
                                                            <a class="icon_list gallery_grid" target="_blank" title="Gallery"  
                                                               onClick="location.href='<?php echo Mage::helper('airhotels')->getimageurl(); ?>id/<?php echo $_product->getId(); ?>'" >
                                                               <?php echo $this->__('Gallery') ?></a>
                                                        </strong>
                                                        <strong class="action_button">
                                                            <a class="icon_list review_grid" target="_blank" title="Reviews"  
                                                               onClick="location.href='<?php echo Mage::getBaseUrl() . "airhotels/property/review/"; ?>id/<?php echo $_product->getId(); ?>'">
                                                               <?php echo $this->__('Reviews') ?></a>
                                                        </strong>
                                                        
                                                    </div>
                                                    </div>
                                                    

                                            </div>
                                            
                                        </div>
                                        <div class="clearfix"></div>

                                        <?php
                                        $c++;
                                    }
                                } else {
                                    ?>
                                    <div class="norecords">
                                        <h2><?php echo $this->__('No Records'); ?></h2>
                                    </div>


                                    <div id="newlist"><input type="button" class="innerpage_btn" id="list"
                                                             name="list" value="<?php echo $this->__('Post new listing'); ?>"
                                                             onClick="location.href='<?php echo Mage::getBaseUrl() . 'restostay/property/form/'; ?>'" />
                                    </div>

                                <?php } ?></div>

                        </div>
                    </div>
                    <!-- Property List Ends-->


                    <!-- Booking History  Starts-->
                    <div id="reserve_div" class="main_content norecords"
                    <?php
                    if (!$this->getRequest()->getParam('from'))
                        echo " style='display:none' "; else
                        echo " style='display:block' class='main_link selected' "
                        ?>>
                        <div id="bookingform">
                            <h2><?php echo $this->__('Booking History'); ?></h2>
                            <div class="clear"></div>
                            <script src="<?php echo Mage::getBaseUrl('js') . 'airhotels/calender/jquery-ui-1.8.16.custom.min.js' ?>"
                            type="text/javascript"></script> <script type="text/javascript">
                                var jQ = jQuery.noConflict();
                                jQ(function() {
                                    jQ( "#bookingfrom, #bookingTo" ).datepicker({
                    
                                        dateFormat: 'yy-mm-dd',
                                        onSelect: function( selectedDate ) {
                                        }
                                    });
                                });
                            </script> <?php
                            $fromDate = $this->getRequest()->getParam('from');
                           $toDate = $this->getRequest()->getParam('to');
                    if ($fromDate)
                        echo "<script> document.getElementById('bookingHistory').className = 'main_link selected';  document.getElementById('manageListing').className = 'main_link'; </script>";
                    ?>
                            <form action="" method="get">
                                <div class="booking_from left">
                                    <h1><?php echo $this->__('From'); ?></h1>
                                    <input type="text" id="bookingfrom" <?php if ($fromDate): ?>
                                               value="<?php echo $fromDate ?>" <?php endif; ?> autocomplete="off"
                                           name="from" value="yyyy-mm-dd"
                                           onfocus="if (this.value=='yyyy-mm-dd') this.value = ''" /></div>
                                <div class="booking_to left">
                                    <h1><?php echo $this->__('To'); ?></h1>
                                    <input type="text" id="bookingTo" <?php if ($toDate): ?>
                                               value="<?php echo $toDate ?>" <?php endif; ?> autocomplete="off"
                                           name="to" value="yyyy-mm-dd"
                                           onfocus="if (this.value=='yyyy-mm-dd') this.value = ''" /></div>
                                <div class="booking_btn left"><input type="hidden" name="clear"
                                                                     value="0" id="bookclear" /> <input type="submit"
                                                                     value="<?php echo $this->__('Search'); ?>" class="innerpage_btn" onclick="return bookingSearch();"/> <input
                                                                     type="submit" value="<?php echo $this->__('Clear'); ?>"
                                                                     style="margin-left: 5px" class="innerpage_btn" onclick="clearForm()" />
                                </div>
                            </form>
                        </div>
                        <?php
                        $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
                        $collection = $this->getBookingHistory();
                        if (count($collection) != 0) {//Productcollection Start

                            ?>
                            <div style="clear: both; margin-top: 10px"></div>
                            <?php if (count($collection) != 0) { ?>
                                <table cellspacing="2" cellpadding="2" border="1" id="booking_property">
                                    <tr>
                                        <th width="10%"><?php echo $this->__('S.No'); ?></th>
                                        <th width="20%"><?php echo $this->__('Property Name'); ?></th>
                                        <th width="10%"><?php echo $this->__('Subtotal'); ?></th>
                                        <th width="10%"><?php echo $this->__('Service Fee'); ?></th>
                                        <th width="10%"><?php echo $this->__('Host Fee'); ?></th>
                                        <th width="20%"><?php echo $this->__('From Date'); ?></th>
                                        <th width="20%"><?php echo $this->__('To Date'); ?></th>
                                    </tr>
                                    <?php
                                    $i = 1;
                                    $config = Mage::getStoreConfig('airhotels/custom_group');
                                    foreach ($collection as $arr_row) {
                                        $entity_id = $arr_row['entity_id'];
                                        $product_collection = Mage::getModel('airhotels/property')->getpropertycollection()
                                                            ->addFieldToFilter(array(array('attribute' => 'userid', 'eq' => $cus_id)));
                                        $product_collection->addFieldToFilter(array(array('attribute' => 'entity_id', 'eq' => $entity_id)));
                                        foreach ($product_collection as $product) {
                                            $arr_row["subtotal"] = Mage::helper('directory')->currencyConvert($arr_row["subtotal"], Mage::app()->getStore()->getBaseCurrencyCode(), Mage::app()->getStore()->getCurrentCurrencyCode());

                                            $arr_row["host_fee"] = Mage::helper('directory')->currencyConvert($arr_row["host_fee"], Mage::app()->getStore()->getBaseCurrencyCode(), Mage::app()->getStore()->getCurrentCurrencyCode());

                                            $arr_row["service_fee"] = Mage::helper('directory')->currencyConvert($arr_row["service_fee"], Mage::app()->getStore()->getBaseCurrencyCode(), Mage::app()->getStore()->getCurrentCurrencyCode());
                                            $dateArr=explode("-",$arr_row["todate"]);
                                            $todate=date('Y-m-d', mktime(0, 0, 0, $dateArr[1], $dateArr[2] + 1, $dateArr[0]));
                                            echo '<tr>';
                                            echo '<td>' . $i . '</td>';
                                            echo '<td>' . $product->getName() . '</td>';
                                            echo '<td>' . $currencySymbol . $arr_row["subtotal"] . '</td>';
                                            echo '<td>' . $currencySymbol . $arr_row["host_fee"] . '</td>';
                                            echo '<td>' . $currencySymbol . $arr_row["service_fee"] . '</td>';
                                            echo '<td>' . date("d, M Y", strtotime($arr_row["fromdate"])) . '</td>';
                                            echo '<td>' . date("d, M Y", strtotime($todate)) . '</td>';
                                            echo '</tr>';
                                            $i++;
                                        }

                                        unset($product_collection);
                                    }
                                } else {
                                    echo '<table cellspacing="2" cellpadding="2" border="1" id="booking_property">';
                                    echo '<tr><td ><font color="red">' . $this->__('Current month no records found') . '</font><td></tr>';
                                }
                                ?>
                            </table>

                            <div style="clear: both"></div>
                            <?php
                        } //Productcollection Start
                        else {
                            if ($fromDate && $toDate)
                                echo "<font color='red'>" . $this->__('No records found') . "</font>";
                        }
                        ?></div>
                    <!-- Booking History Ends-->        
                    <div class="clear"></div>
                </div>


            </div>
        </div>

    </div>
</div>
<script type="text/javascript">
    function airbnbActivate(pStatus,buttonId,element)
    {
        document.getElementById(element).style.display = "none";
        document.getElementById("loadingSpace"+buttonId).innerHTML = "<img src='<?php echo $this->getSkinUrl('images/ajax-loader-small.gif'); ?>' />";
        var xmlhttp = getHttp();
        xmlhttp.onreadystatechange=function()
        {
            if (xmlhttp.readyState==4 && xmlhttp.status==200)
            {
                if(xmlhttp.responseText=="Available"){
                    document.getElementById("active"+buttonId).style.display ="none";
                    document.getElementById("hide"+buttonId).style.display ="block";
                   
                }
                else{
                    document.getElementById("active"+buttonId).style.display="block";
                    document.getElementById("hide"+buttonId).style.display ="none";
                }
                document.getElementById("loadingSpace"+buttonId).innerHTML = "";
                window.location.href = "<?php echo Mage::helper('airhotels')->getyourlisturl() ?>"; 
                //document.getElementById("calendarWrapper").innerHTML=xmlhttp.responseText;
            }
        }
        var productId = document.getElementById("productId"+buttonId).value;
        xmlhttp.open("GET","<?php echo Mage::getBaseUrl() . 'airhotels/property/status/' ?>"+"?status="+pStatus+"&buttonid="+buttonId+"&productid="+productId,true);
        xmlhttp.send();
    }
    function getHttp(){
        var xmlhttp;
        if (window.XMLHttpRequest)
        {// code for IE7+, Firefox, Chrome, Opera, Safari
            xmlhttp=new XMLHttpRequest();
        }
        else
        {// code for IE6, IE5
            xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
        }
        return xmlhttp;
    }

    function bookingSearch(){
        var fromDate = jQuery("#bookingfrom").val();
        var toDate = jQuery("#bookingTo").val();
        if(fromDate == "" || fromDate == "yyyy-mm-dd" || toDate == "" || toDate == "yyyy-mm-dd"){

           alert('Selected date is incorrect,please select the correct date');
          return false;
        }
    }
    function clearForm(){
        jQuery("#bookingfrom").attr("value","yyyy-mm-dd");
        jQuery("#bookingTo").attr("value","yyyy-mm-dd");
        jQuery("#bookclear").attr("value","1");
    }
</script>




