<link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'/>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
<script type="text/javascript">
    function initialize() {
        var mapOptions = {
            //center: new google.maps.LatLng(-33.8688, 151.2195),
            zoom: 13,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById('map_canvas'),
        mapOptions);

        var input = document.getElementById('searchTextField');
        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.bindTo('bounds', map);
        // Autocomplete.
        function setupClickListener(id, types) {
            var radioButton = document.getElementById(id);
            google.maps.event.addDomListener(radioButton, 'click', function() {
                autocomplete.setTypes(types);
            });
        }

    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<?php
$count = 1;
$threeDiv = 1;
$model = Mage::getModel('catalog/product');
$baseurl = Mage::getBaseUrl('skin');


$_productCollection = Mage::getModel('airhotels/property')->getpropertycollection()
                ->addAttributeToFilter('status', array('eq' => 1))
                ->setPageSize(10)->setOrder('created_at', 'desc')->addAttributeToSelect('*');
$currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
//if(count($_productCollection)!= 0){

?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('jcarousel/jquery.jcarousel.min.js')?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('jcarousel/skin.css')?>" />
<script type="text/javascript">
function mycarousel_initCallback(carousel)
{
    // Disable autoscrolling if the user clicks the prev or next button.
    carousel.buttonNext.bind('click', function() {
        carousel.startAuto(0);
    });

    carousel.buttonPrev.bind('click', function() {
        carousel.startAuto(0);
    });

    // Pause autoscrolling if the user moves with the cursor over the clip.
    carousel.clip.hover(function() {
        carousel.stopAuto();
    }, function() {
        carousel.startAuto();
    });
};

jQuery(document).ready(function() {	
	jQuery('#menuwhatnew').jcarousel();
});

</script>



<!-- Scroll most rated js -->

  <script type="text/javascript" src="http://www.dev.restostay.com/js/scroll/jquery-1.3.2.min.js"></script> 
  <script type="text/javascript" src="http://www.dev.restostay.com/js/scroll/jcarousellite_1.0.1.pack.js"></script> 
 	
      <script type="text/javascript">
		 
		jQuery(function() {
			
    		jQuery(".slider").jCarouselLite({
        		
        		//btnPrev: ".prev",
				//btnPrev1: ".prev",
				visible: 4
    		});
		});
		
		
	</script>
   
    <style>
	
.slider {
	float:left;
	left: -5000px; 
	padding:0 15px; 
	position:relative; 
	visibility:hidden;
	border: 1px solid #9c1e1f;
	width:968px !important;	
}
 
.prev {
	cursor:pointer; 
	float:left;
	padding-top:60px;
}

.next {
	cursor:pointer; 
	float:right; 
	padding-top:60px;
}






    </style>

<!-- end -->
<div class="clear"></div>
<div id="roomshomepage">
    <div id="room" class="clearfix">
        <div id="left_columnhomepage">
            <div id="main_content" class="box">
                <div class="tabhomepage">
                    
                    <ul id="main_content_sub_navhomepage" class="rooms_sub_navhomepage clearfix ">
                        <li id="menuwhatnew" class="main_link selected">
                            <a href="#whatnew" onclick="showTabs('whatsnew','menuwhatnew')"><?php echo $this->__('What\'s New'); ?></a>
                        </li>
                        <li id="menuRated" class="main_link">
                            <a href="#mostrated" onclick="showTabs('rated_div','menuRated')"><?php echo $this->__('Most Rated'); ?></a>
                        </li>
                        <li id="menuPopular" class="main_link">
                            <a href="#mostrated" onclick="showTabs('popular_div','menuPopular')"><?php echo $this->__('Most Popular'); ?></a>
                        </li>
                            
<!--                        <li id="content_flag">
                            
                        </li>-->
                    </ul>
                   
                    <div id="whatsnew" class="main_content" style="display: block; ">
                    
                   <!--  <div class="prev"><img onclick="return wn(leftname.value)" src="images/prev.jpg" alt="prev" /></div> -->
                    <div class="slider">
                       <marquee onmouseover="this.stop();" onmouseout="this.start();" loop="repeat">
                        <ul id="homepage_badges" class="first-and-second-carousel jcarousel-skin-tango rounded tab-section" style="display: block;<?php if(count($_productCollection)== 0 ) echo "text-align: center;" ?> ">
                        
                            <?php
                           if(count($_productCollection)!= 0 ){
                            $count = 1;
                            foreach ($_productCollection as $_product):
                                if ($count <= 5):
                                    ?>
                         
                            <?php
                                $mainimage=$this->helper('catalog/image')->init($_product, 'image')
                                ->constrainOnly(TRUE)
                                ->keepAspectRatio(TRUE)
                                ->keepFrame(FALSE)
                                ->resize(200,null)
                            ?>
                           
                                    <li class="rounded" <?php if($count == 4) { echo 'style=" margin-right:0;" ' ;}?>>
                                        <a class="ss_name" href="<?php echo Mage::getBaseUrl() . $_product->getUrlPath(); ?>"  >
                                            <img src="<?php
                            if ($_product->getImage() != 'no_selection') {
                                echo $mainimage;
                            } else { 
                                echo $_product->getImageUrl();
                            }
                                    ?>" width="230" height="140" title="<?php echo substr($_product->getName(), 0, 25); ?>" class="captify" >
                                        </a>
                                        <div class="box-shadow">
                                             <a href="<?php echo Mage::getBaseUrl() . $_product->getUrlPath(); ?>" style="text-decoration: none;">
                                            <?php echo substr($_product->getName(), 0, 30); ?>
                                             </a>
                                        </div>
                                    </li>
                                    
                                    <?php
                                endif;
                                $count++;
                            endforeach;
                           }else{
                               echo $this->__('No Records!');

                           }
                            ?>
                            
                           
                        </ul>
                        </marquee>
                        </div>
                        <!-- <div class="next"><img id="homepage_badges1" src="images/next.jpg" alt="next" onclick="return test(count.value)"  /> </div> -->
                        
                    </div>
                    <!-- most rated -->
                    <?php $rateCollection = Mage::getModel('airhotels/property')->getRatedProperty();?>
                    <div id="rated_div" class="main_content" style="display: none;">
                    
                   <!-- <div class="prev"><img src="images/prev.jpg" alt="prev" onclick="return mrated(leftname.value)" /></div> -->
                    	<div class="slider" id="slider1">
                     <marquee onmouseover="this.stop();" onmouseout="this.start();" loop="repeat">
                        <ul id="rated_badges" class="first-and-second-carousel jcarousel-skin-tango rounded tab-section" style="display: block; <?php if(count($rateCollection)== 0 ) echo "text-align: center;" ?>">
                            <?php
                             if(count($_productCollection)!= 0 ){
                              $countRate = 1;
                            foreach ($rateCollection as $rateProduct) { //echo "test";
                            ?>
                             <?php
                                $rateimage=$this->helper('catalog/image')->init($rateProduct, 'image')
                                ->constrainOnly(TRUE)
                                ->keepAspectRatio(TRUE)
                                ->keepFrame(FALSE)
                                ->resize(200,null)
                            ?>
                                <li class="rounded rated" <?php if($countRate == 4) { echo 'style=" margin-right:0;" ' ;}?>>
                                    <a class="ss_name" href="<?php echo Mage::getBaseUrl() . $rateProduct->getUrlPath(); ?>">
                                        <img alt="" src="<?php
                            if ($rateProduct->getImage() != 'no_selection') {
                                echo Mage::getBaseUrl('media') . 'catalog/product/' . $rateProduct->getImage();
                            } else {
                                echo $rateProduct->getImageUrl();
                            }
                                ?>" width="230" height="140" title="<?php echo substr($rateProduct->getName(), 0, 25); ?>" class="captify">
                                    </a>
                                    <div class="box-shadow">
                                         <a href="<?php echo Mage::getBaseUrl() . $rateProduct->getUrlPath(); ?>" style="text-decoration: none;">
                                        <?php echo substr($rateProduct->getName(), 0, 30); ?>
                                         </a>
                                    </div>
                                </li>
                            <?php 
                              $countRate++;
                                }
                             }else{
                               echo $this->__('No Records!');

                           }
                            ?>
                        </ul>
                        </marquee>
                        </div>
                       <!-- <div class="next"><img src="images/next.jpg" alt="next" onclick="return abc(count.value);" /> </div> -->
                      
                    </div>
                    <!-- most rated ends -->
                    <!-- most popular -->
                     <?php
                    $rateCollection = Mage::getModel('airhotels/property')->getPopularProperty();
                    ?>
                    <div id="popular_div" class="main_content" style="display: none;">
                    
                    
                    <div class="slider" id="slider2">
                       <marquee onmouseover="this.stop();" onmouseout="this.start();" loop="repeat" width="100%" behavior="scroll">
                       
                        <ul id="popular_badges" class="popular_badges1">
                            <?php
                         if(count($rateCollection)!= 0 ){
                             
                           $countPopular = 1;
                            for ($s = 0; $s < count($rateCollection); $s++) {
                                $popularCollection = $model->load($rateCollection[$s]["entity_id"]);
                                //if ($popularCollection->getImage() != "no_selection" && trim($popularCollection->getImage()) != ""):
                                ?>
                                <li class="rounded round" <?php if($countPopular == 4) { echo 'style=" margin-right:0;" ' ;}?>>
                                    <a class="ss_name" href="<?php echo Mage::getBaseUrl() . $popularCollection->getUrlPath(); ?>">
                                        <img alt="" src="<?php
                            if ($popularCollection->getImage() != "no_selection") {
                                echo Mage::getBaseUrl('media') . 'catalog/product/' . $popularCollection->getImage();
                            } else {
                                echo $popularCollection->getImageUrl();
                            }
                                ?>" width="230" height="140" title="<?php echo substr($popularCollection->getName(), 0, 25); ?>">
                                    </a>
                                    <div class="box-shadow">
                                        <a href="<?php echo Mage::getBaseUrl() . $popularCollection->getUrlPath(); ?>" style="text-decoration: none;">
                                        <?php echo substr($popularCollection->getName(), 0, 30); ?>
                                        </a>
                                    </div>
                                </li>
                                <?php
                               $countPopular++;
                             }
                             }else{
                               echo $this->__('No Records!');

                           }
                            ?>
                        </ul>
                        
                        </marquee>
                        </div>
                       <!-- <div class="next"><img onclick="return most(count.value)" src="images/next.jpg" alt="next" /> </div> -->
                       
                    </div>
                    <!-- most popular -->
                        
                        
                </div>
                    
                    
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var $slide = jQuery.noConflict();
    function showTabs(id,menuName){ 
        $slide(".main_content").hide();
        $slide(".main_link").removeClass("selected");
        $slide("#"+menuName).addClass("selected");
        $slide("#"+id).show();
		
		document.getElementById("leftname").value="";
		document.getElementById("count").value=1;
		
		
		jQuery(".popular_badges1").removeAttr('style');
		
		jQuery("#slider1").removeAttr('style');
		jQuery('#slider1').attr('style', 'width: 980px !important; left: 0; overflow: hidden; position: relative; visibility: visible; z-index: 2');
		
		
		jQuery('.rated').attr('style', 'width: 230px !important; height: 140px; float: left; overflow: hidden;');
    	
		jQuery("#rated_badges").removeAttr('style');
		
		
		
		
		jQuery("#slider2").removeAttr('style');
		jQuery('#slider2').attr('style', 'width: 980px !important; left: 0; overflow: hidden; position: relative; visibility: visible; z-index: 2');
		jQuery('.round').attr('style', 'width: 230px !important; height: 140px; float: left; overflow: hidden;');
		
	
    }
	
	
	
	
	
	
	
	/*function abc(count){
		
    	if (count > 1) {
			var v = document.getElementById("leftname").value;
			 var nv = parseInt(v)+parseInt(178);
			jQuery("#rated_badges").attr('style','width:3185px; left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
			
			document.getElementById("leftname").value= nv;
			
			
     
    	}
		else
		{
		jQuery("#rated_badges").attr('style', 'width:3185px; left:-250px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= 250;
	
		}
		count++;
		document.getElementById("count").value=count;
			
	}
	
	function test(count){
		
    	if (count > 1) {
			var v = document.getElementById("leftname").value;
			 var nv = parseInt(v)+parseInt(178);
			jQuery("#homepage_badges").attr('style','left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
			document.getElementById("leftname").value= nv;
			
			
      
    	}
		else
		{
		jQuery("#homepage_badges").attr('style', list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= 250;
	
		}
		count++;
		document.getElementById("count").value=count;
  		
		
				
		
	}
	
	function most(count){
		
    	if (count > 1) {
			var v = document.getElementById("leftname").value;
			 var nv = parseInt(v)+parseInt(178);
			 
			jQuery("#popular_badges").attr('style','width:3185px; left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
			document.getElementById("leftname").value= nv;
     
    	}
		else
		{
		jQuery("#popular_badges").attr('style', list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= 250;
	
		}
		count++;
		document.getElementById("count").value=count;
  		
		
	}
	
	
	
	function mrated(){
		
		var v = document.getElementById("leftname").value;
		var nv = parseInt(v)-parseInt(178);
		
		jQuery("#rated_badges").attr('style',left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= nv;
			
	}
	
	
	function wn(){
		//alert("test");
		var v = document.getElementById("leftname").value;
		var nv = parseInt(v)-parseInt(178);
		//alert(nv);
		jQuery("#homepage_badges").attr('style', left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= nv;
			
	}
	
	function mp(){
		//alert("test");
		var v = document.getElementById("leftname").value;
		var nv = parseInt(v)-parseInt(178);
		//alert(nv);
		jQuery("#popular_badges").attr('style',left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= nv;
			
	}
	
	
	jQuery(document).ready(function(){
		
		jQuery("#homepage_badges").removeAttr('style');	
		jQuery(".slider").removeAttr('style');
		jQuery('.slider').attr('style', 'width: 3250 !important; left: 0; overflow: hidden; position: relative; visibility: visible; z-index: 2');
	});*/
</script>

<input type="hidden" name="leftname" id="leftname" value=""  />
<input type="hidden" name="count" id="count" value="1"  />
<input type="hidden" name="previ" id="previ" value=""  />