

<script type="text/javascript" src="http://maps.google.com/maps/api/js?libraries=adsense&sensor=false"></script>


<script src='http://j.maxmind.com/app/geoip.js' type='text/javascript'></script>
<style type="text/css">
#map{display:none}
#sidewrap{display:none;}
#panelwrap{display:none;}#hidetabs{width:1px;height:1px;color:#ffffff;overflow:hidden;}
#map1,#map2{display:none}
</style>

		  	<div id="map1" style="height:250px"></div>

<div id="ms">
	<script type="text/javascript">
var gmarkers = [];
var myLatlng1 = new google.maps.LatLng(53.463066,-2.291309);


var myOptions1 = {
      zoom: 15,
      center: myLatlng1,
      mapTypeId: google.maps.MapTypeId.ROADMAP
}


var infoWindow = new google.maps.InfoWindow;
document.getElementById("map1").style.display = 'block';

var map1 = new google.maps.Map(document.getElementById("map1"), myOptions1);


function createMarkerMap(point,map,infoWindow,html,name) {
var marker = new google.maps.Marker({position:point,map:map,title:name}); 
google.maps.event.addListener(marker, 'click', function() { 
infoWindow.setContent(html); 
infoWindow.open(map,marker); 
});

gmarkers.push(marker);

return marker;
}

var point = new google.maps.LatLng(53.463066,-2.291309);
var name ='Man Utd';
var html = '<div style="width:240px">Old Trafford<\/div>';
var marker = createMarkerMap(point,map1,infoWindow,html,name);
 
</script></div>