<?php
/**
 * @ Author     : Apptha team
 * @copyright   : Copyright (c) 2011 (www.apptha.com)
 * @license     : http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!--begin custom header content for this example-->


<!--end custom header content for this example-->
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<script>
		var jq = jQuery.noConflict();
		jq(document).ready(function(){
			
			jq("a[rel='product-image']").colorbox({transition:"fade",slideshow:true});			
			
		});
	</script>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views media-images">
    
	    <ul>
	    <?php 
	    foreach ($this->getGalleryImages() as $_image): ?>
	        <li>
	            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" rel="product-image"  title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(80); ?>" width="80" height="80" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
	        </li>
	    <?php endforeach;
		
	    ?>
	    </ul>
</div>
<?php 
else: ?>
	<span><?php echo  $this->__('No images available') ?></span>
<?php 
endif; ?>