<link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'/>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>


<script type="text/javascript">
    function initialize() {
        var mapOptions = {
            //center: new google.maps.LatLng(-33.8688, 151.2195),
            zoom: 13,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById('map_canvas'),
        mapOptions);

        var input = document.getElementById('searchTextField');

        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.bindTo('bounds', map);
        // Autocomplete.
        function setupClickListener(id, types) {
            var radioButton = document.getElementById(id);
            google.maps.event.addDomListener(radioButton, 'click', function() {
                autocomplete.setTypes(types);
            });
        }

    }
    google.maps.event.addDomListener(window, 'load', initialize);
    var $s = jQuery.noConflict();
    function validateSearch(){
        $s("#searchResult").html("");
        $s("#searchTextField").css("border-color","#D2D2D2");
        window.location.href = "<?php echo Mage::getBaseUrl() . 'airhotels/property/advsearch/' ?>";
        $s("#searchResult").html("Please set location");
        return true;
    }
      
        var jQ = jQuery.noConflict();
            jQ(function() {
                    //jQ('input[placeholder]').placeholder();


                    var dates = jQ( "#checkinDate, #checkinTo" ).datepicker({
                            //defaultDate: "+1w",
                            changeMonth: true,
                            numberOfMonths: 1,
                            minDate: '0',
                            onSelect: function( selectedDate ) {
                                    var option = this.id == "checkinDate" ? "minDate" : "maxDate",
                                            instance = jQ( this ).data( "datepicker" ),
                                            date = jQ.datepicker.parseDate(
                                                    instance.settings.dateFormat ||
                                                    jQ.datepicker._defaults.dateFormat,
                                                    selectedDate, instance.settings );
                                    dates.not( this ).datepicker( "option", option, date );
                                    jQ("#checkinDate" ).datepicker("option","maxDate","");

                                    if(this.id == "checkinDate"){
                                            instance = jQ( this ).data( "datepicker" )
                                            var depart = jQ.datepicker.parseDate(jQ.datepicker._defaults.dateFormat, selectedDate);
                                            depart.setDate(depart.getDate() + 1);
                                            jQ("#checkinTo" ).datepicker(  "option", "minDate", depart );
                                    }
                            }
                    });
            });

       
        </script>



<div id="examples_outer">
    <div id="slider_container_2">
        <div class="search-area">
            <div class="container">
                <div class="banner_outer">
                    <div class="banner_transparent">
                        <h1><?php echo $this->__('Explore great place to stay!') ?></h1>
                        <h2><?php echo $this->__('Let it be from any part of the world, make it yours!') ?></h2>
                    </div>
                </div>

                <form action="<?php echo Mage::getBaseUrl() . 'restostay/property/advsearch/' ?>" id="search" name="search" method="get" enctype="multipart/form-data" class="custom">

                    <input id="searchTextField" name="searchTextField" type="text" class="searchmainpage"  placeholder="<?php echo $this->__('Where are you going') . "?"; ?>" onfocus="if (this.placeholder == '<?php echo $this->__('Where are you going') . "?"; ?>') {this.placeholder = '';this.style.color ='#E10979';}" onblur="if (this.placeholder == '') {this.style.color ='#E10979';this.placeholder = '<?php echo $this->__('Where are you going') . "?"; ?>';}"/>
                     <div id="search_options" class=" left" style="">
                            <div class="search_date">
<!--                              <div class="checkinDate"><?php echo  $this->__('Check in'); ?> </div>-->
                              <input type="text"  id="checkinDate"  name="from"   placeholder="mm/dd/yyyy" autocomplete="off" >
                            </div>
                            <div class="search_date">
<!--                                <div class="checkinDate"><?php echo  $this->__('Check out'); ?></div>-->
                              <div><input type="text"   id="checkinTo"  name="to"  placeholder="mm/dd/yyyy" autocomplete="off"></div>
                            </div>

                            <div class="search_guests">
<!--                              <div class="checkinDate"><?php echo  $this->__('Guests') ?></div>-->
                                  <select id="number_of_guests" name="number_of_guests">
                                       <option value="1" selected="selected"><?php echo $this->__('1 Guest'); ?></option>
                                        <option value="2" >2 Guest</option>
                                        <option value="3">3 Guests</option>
                                        <option value="4">4 Guests</option>
                                        <option value="5">5 Guests</option>
                                        <option value="6">6 Guests</option>
                                        <option value="7">7 Guests</option>
                                        <option value="8">8 Guests</option>
                                        <option value="9">9 Guests</option>
                                        <option value="10">10 Guests</option>
                                        <option value="11">11 Guests</option>
                                        <option value="12">12 Guests</option>
                                        <option value="13">13 Guests</option>
                                        <option value="14">14 Guests</option>
                                        <option value="15">15 Guests</option>
                                        <option value="16">16+ Guests</option>
                                  </select>
                            </div>
                        </div>
                         <button type="submit" class="large pink btn icon-only" id="submit_location" onclick="return validateSearch();">
                    SEARCH</button>

                    <div id="map_canvas" style="width:427px;"></div>
                </form>

            </div>
        </div>
        <?php
        $model = Mage::getModel('catalog/product');

        $baseurl = Mage::getBaseUrl('skin');
        $_productCollection = Mage::getModel('airhotels/property')->getpropertycollection()
                        ->addAttributeToFilter('status', array('eq' => 1))
                        ->setPageSize(10)->setOrder('created_at', 'desc')->addAttributeToSelect('*');

        $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
        if (count($_productCollection)) {
            ?>
            <div id="SliderName_2" class="SliderName_2">
                <?php
                foreach ($_productCollection as $_product) {
                    ?>

                    <a class="ss_name" href="<?php echo Mage::getBaseUrl() . $_product->getUrlPath(); ?>">
                        <?php if ($_product->getImage() != 'no_selection') { ?>
                            <img src="<?php echo Mage::getBaseUrl('media') . 'catalog/product/' . $_product->getImage(); ?>"alt="Demo2 first" title="Demo2 first" style="height: auto !important;" />
                        <?php } else { ?>
                            <img src="<?php echo $_product->getImageUrl(); ?>"  alt="Demo2 first" title="Demo2 first"  style="height: auto !important;"/>
                        <?php }
                        ?> </a>

                    <div class="SliderName_2Description">
                        <div id="slider_showface">
                            <?php $customerData = Mage::getModel('airhotels/airhotels')->getCustomerPictureById($_product->getUserid()); ?>
                            <?php if ($customerData[0]["imagename"]): ?>
                                <?php                                
                                $imageResized = Mage::getBaseDir("media") . "/catalog/customer/resz_" . $customerData[0]["imagename"];
                                $imageDirUrl  = Mage::getBaseDir("media") . "/catalog/customer/" . $customerData[0]["imagename"];
                                if (!file_exists($imageResized) && file_exists($imageDirUrl)) :
                                    $imageObj = new Varien_Image($imageDirUrl);
                                    $imageObj->constrainOnly(TRUE);
                                    $imageObj->keepAspectRatio(TRUE);
                                    $imageObj->keepFrame(FALSE);
                                    $imageObj->resize(72, 72);
                                    $imageObj->save($imageResized);
                                endif;                                
                                $imageUrl = Mage::getBaseUrl('media') . "catalog/customer/" . $customerData[0]["imagename"];
                                if (file_exists($imageResized)) {
                                    $imageUrl = Mage::getBaseUrl('media') . "catalog/customer/resz_" . $customerData[0]["imagename"];
                                }
                                ?>
                                <img src="<?php echo $imageUrl; ?>"
                                     class="face_img" height="86" alt="" title=""/>
                            <?php else: ?>
                                <img src="<?php echo $this->getSkinUrl('images/home_no_user.jpg'); ?>" class="face_img" alt="" title=""/>
                            <?php endif; ?>
                            <div class="right_desc">
                                <h3><a class="ss_name"
                                       href="<?php echo Mage::getBaseUrl() . $_product->getUrlPath(); ?>"><?php echo $this->htmlEscape($_product->getName()); ?></a></h3>
                                <span><?php
                echo $this->htmlEscape($_product->getCity()) . ', ';
                echo $this->htmlEscape($_product->getCountry());
                            ?> </span>
                                <span class="bottom_descs">
                                    <?php
                                    $reviews = Mage::getModel('review/review')->getResourceCollection();
                                    $reviews->addStoreFilter(Mage::app()->getStore()->getId())
                                            ->addStatusFilter(Mage_Review_Model_Review::STATUS_APPROVED)
                                            ->addEntityFilter('product', $_product->getId())
                                            ->setDateOrder()
                                            ->addRateVotes();
                                    $reviews = $reviews->getData();
                                    ?>
                                    &nbsp;-&nbsp;<span><?php echo $currencySymbol . ' ' . round(Mage::helper('directory')->currencyConvert($_product['Price'], Mage::app()->getStore()->getBaseCurrencyCode(), Mage::app()->getStore()->getCurrentCurrencyCode()), 0) . '/ '.$this->__('Night') ?></span>
<!--                                    <strong class="floatright">
                                        <?php
                                        $rating = Mage::getModel('airhotels/airhotels')->getCustomerRatings($_product->getId());
                                        $sum = 0;
                                        for ($i = 0; $i < count($rating); $i++) {
                                            $sum +=$rating[$i]["percent"];
                                        }
                                        $avgRating = $sum / count($rating);

                                        if ($avgRating > 1 && $avgRating <= 20) {
                                            Apptha_Airhotels_Block_Airhotels::showratingCode(1);
                                        } else if ($avgRating > 21 && $avgRating <= 40) {
                                            Apptha_Airhotels_Block_Airhotels::showratingCode(2);
                                        } else if ($avgRating > 41 && $avgRating <= 60) {
                                            Apptha_Airhotels_Block_Airhotels::showratingCode(3);
                                        } else if ($avgRating > 61 && $avgRating <= 80) {
                                            Apptha_Airhotels_Block_Airhotels::showratingCode(4);
                                        } else if ($avgRating > 81 && $avgRating <= 100) {
                                            Apptha_Airhotels_Block_Airhotels::showratingCode(5);
                                        } else {
                                            Apptha_Airhotels_Block_Airhotels::showratingCode(0);
                                        }


                                        echo "&nbsp;" . " (" . count($reviews);
                                        echo " " . $this->__('Reviews)');
                                        ?>

                                    </strong>-->
                                </span>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <?php
                }
            }
            ?>
        </div>

        <script type="text/javascript">
            effectsDemo2 = 'fade';
            var myWidth;
            if( typeof( window.innerWidth ) == 'number' ) {
                //Non-IE
                myWidth = window.innerWidth;
            } else if( document.documentElement &&
                document.documentElement.clientWidth ) {
                //IE 6+ in 'standards compliant mode'
                myWidth = document.documentElement.clientWidth;
            } else if( document.body && document.body.clientWidth ) {
                //IE 4 compatible
                myWidth = document.body.clientWidth;
            }
            var demoSlider_2 = Sliderman.slider({container: 'SliderName_2', width: myWidth, height: 548, effects: effectsDemo2,
                display: {
                    autoplay: 5000,
                    buttons: {hide: true, prev: {className: 'SliderNamePrev_2', label: ''}, next: {className: 'SliderNameNext_2', label: ''}},
                    description: {hide: true,  height: 122, position: 'bottom'}

                }
            });
        </script>


    </div>

</div>
