<?php if ($this->getCurrencyCount() > 0): ?>
    <span style="display:none">Select Currency:</span>

<?php
    $actionName = $this->getRequest()->getActionName();
    $queryString = "";
    $currentURL = Mage::helper('core/url')->getCurrentUrl().$queryString;
    if ($actionName == 'advsearch') {
        $searchText = $this->getRequest()->getParam('searchTextField');
        $from = str_replace("/","-",$this->getRequest()->getParam('from'));
        $to = str_replace("/","-",$this->getRequest()->getParam('to'));
        $noOfGuest = $this->getRequest()->getParam('number_of_guests');        
        $queryString = "searchTextField/" . $searchText . "/from/" . urlencode($from) . "/to/" . urlencode($to) . "/number_of_guests/" . $noOfGuest;
        $currentURL = Mage::getBaseUrl() . 'restostay/property/advsearch/'.$queryString;
    }   
    function getCurrenyURL($_code, $url) {
        $params = array('currency' => $_code);        
        $params[Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED] = Mage::helper('core')->urlEncode($url);
        return Mage::getUrl('directory/currency/switch', $params);
    }
?>

    <select name="custom-currency-selector" id="custom-currency-selector"  onchange="window.location.href=this.value" style="padding: 0px">
    <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
        <option value="<?php echo getCurrenyURL($_code, $currentURL) ?>"
    <?php if ($_code == $this->getCurrentCurrencyCode()): ?>
                    selected="SELECTED"
            <?php endif; ?>>
                <?php echo $_code ?>
    </option>
    <?php endforeach; ?>
            </select>


<?php endif; ?>
<!--<div class="skinnedSelect">
        <div class="text" id="text1">One</div>
        <select name="name" onChange="setText('text1', this);">
      		<option value="1">One</option>
      		<option value="2">Two</option>
      		<option value="3">Three</option>
      	</select>
      </div>-->
<script type="text/javascript">



    //jQuery.noConflict()
    //(function($cur) {
    //    //now I can use $ locally
    //})(jQuery)
    //    $cur('custom-currency-selector').observe('change',function(evt){
    //        window.location = $('custom-currency-selector').value;
    //    });
</script>