<style type="text/css">
    .page{background-image:none }
    .Err{color:red}
</style>
<?php
  $customer_id = $this->getRequest()->get('cid');
  $customer_data = Mage::getModel('customer/customer')->load($customer_id);
  $productId = $this->getRequest()->get('pid');
$model = Mage::getModel('catalog/product'); //getting product model
$_product = $model->load($productId);
$accommodate = $_product->getAccomodates();
?>
    <div class="sendMessage">
    <h2> <?php echo $this->__("Send Message to"). ucfirst($customer_data->getFirstname()) . ","; ?> </h2>
    </div>
    <script type="text/javascript">
    <!--
    var jQ = jQuery.noConflict();
	jQ(function() {
		var dates = jQ( "#checkinDate, #checkinTo" ).datepicker({
			changeMonth: true,
			numberOfMonths: 1,
                        minDate: '0',
			onSelect: function( selectedDate ) {
				var option = this.id == "checkinDate" ? "minDate" : "maxDate",
					instance = jQ( this ).data( "datepicker" ),
					date = jQ.datepicker.parseDate(
						instance.settings.dateFormat ||
						jQ.datepicker._defaults.dateFormat,
						selectedDate, instance.settings );
				dates.not( this ).datepicker( "option", option, date );
                jQ("#checkinDate" ).datepicker("option","maxDate","");

                if(this.id == "checkinDate"){
                    instance = jQ(this).data( "datepicker" );
                    var depart = jQ.datepicker.parseDate(jQ.datepicker._defaults.dateFormat, selectedDate);
                    depart.setDate(depart.getDate() + 1);
                    jQ("#checkinTo" ).datepicker(  "option", "minDate", depart );

			}

            }
		});
	});
        
        function validateForm(){
            var errFlag = false;
            jQ(".Err").html("");
            var checkinDate  = jQ.trim(jQ("#checkinDate").val());
            var checkinTo  = jQ.trim(jQ("#checkinTo").val());
        var mailSubject = jQ.trim(jQ("#mailSubject").val());

        if(checkinDate == ""){

            	jQ("#checkinDateErr").html("Check in date");
                 errFlag = true;
            }
            if(checkinTo == ""){
            jQ("#checkinToErr").html("Check out date");
                errFlag = true;
            }
            if(mailSubject == ""){
            	jQ("#mailSubjectErr").html("Please fill mail subject");
                errFlag = true;
            }
            if(errFlag)
                return false;
            else
                return true;
        }
        function ajaxLoadCalendar(pUrl)
        {
            //document.getElementById("calendarWrapper").innerHTML = "<img src='ajax-loader.gif' />";
            document.getElementById("calendarWrapper").innerHTML="<div style='margin:50px 0px 50px 0px;' ><img  src='<?php echo $this->getSkinUrl('images/calendar-loader.gif')?>' /></div>";
            
            var xmlhttp = getHttp();
            xmlhttp.onreadystatechange=function()
              {
              if (xmlhttp.readyState==4 && xmlhttp.status==200)
                {
                    document.getElementById("calendarWrapper").innerHTML=xmlhttp.responseText;
                }
              }
            xmlhttp.open("GET",pUrl+"&ajax",true);
            xmlhttp.send();
        }

        function getHttp(){
            var xmlhttp;
            if (window.XMLHttpRequest)
              {// code for IE7+, Firefox, Chrome, Opera, Safari
              xmlhttp=new XMLHttpRequest();
              }
            else
              {// code for IE6, IE5
              xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
              }
              return xmlhttp;
        }
    //-->
    </script>

    <form action="<?php echo Mage::getBaseUrl()."airhotels/property/saveinbox" ?>" method="post">
        <div id="search_options" class="clearfix">

                        <div class="search_date">
                          <div class="checkinDate"><?php echo $this->__('Check in'); ?> </div>
                          <input type="text" placeholder="dd-mm-yy" autocomplete="off"  id="checkinDate"  name="from" style="color: black;" >
                          <div id="checkinDateErr" class="Err"></div>
                        </div>
                        <div class="search_date">
                            <div class="checkinDate"><?php echo $this->__('Check out'); ?></div>
                            <div><input type="text" placeholder="dd-mm-yy" autocomplete="off"  id="checkinTo"  name="to" style="color: black;"></div>
                            <div id="checkinToErr" class="Err"></div>
                        </div>

                        <div class="search_guests">
                          <div class="checkinDate"><?php echo $this->__('Guests'); ?></div>
                              <select id="number_of_guests" name="number_of_guests">
                <?php for ($i = 1; $i <= $accommodate; $i++) { ?>
                    <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                <?php } ?>
                                  </select>
                        </div>
            </div>
        <div class="contact_form">
            <p >
                <?php $this->__('Tell') ?> <?php echo ucfirst($customer_data->getFirstname()); ?>, <?php echo $this->__('what you like about their place, what matters most about your accommodations, or ask them a question.'); ?>
            </p>
            <div>
                <textarea name="mailSubject" id="mailSubject"></textarea>
                <div id="mailSubjectErr" class="Err"></div>
            </div>
        </div>
        <div style="margin: 25px 0 0">
            <h1 style="color:#333;font-family: 'abel';font-size: 18px;font-weight: bold;"><?php echo $this->__('Can this host call you about your inquiry?'); ?></h1>
        <div ><input type="radio" name="hostCall" id="hostCall" value="1" id="popup_radio" checked="true"/><font style="padding-left: 5px;"><?php echo $this->__('Yes') ?></font>
           <span style="padding-left: 20px;"> <input type="radio" name="hostCall" id="hostCall" value="0" /><font style="padding-left: 5px;"><?php echo $this->__('No') ?></font></span></div>
        </div> 
        <p class="time_zone">
            <?php echo $this->__("Your number won't be revealed. They can only call from 9am to 9pm in your time zone.") ?>
        </p>
        
            <div>
             <select id="guest_preferences_time_zone" name="guest_preferences"><option value="International Date Line West"><?php $this->__('(GMT-11:00) International Date Line West') ?></option>
                    <option value="<?php echo $this->__("(GMT-11:00) Midway Island"); ?>"><?php echo $this->__("(GMT-11:00) Midway Island"); ?> </option>
                    <option value="<?php echo $this->__("(GMT-11:00) Samoa"); ?>"><?php echo $this->__("(GMT-11:00) Samoa"); ?></option>
                    <option value="<?php echo $this->__("(GMT-10:00) Hawaii"); ?>"><?php echo $this->__("(GMT-10:00) Hawaii"); ?></option>
                    <option value="<?php echo $this->__("(GMT-09:00) Alaska"); ?>"><?php echo $this->__("(GMT-09:00) Alaska"); ?></option>
                    <option value="<?php echo $this->__("(GMT-08:00) Pacific Time (US &amp; Canada)"); ?>"><?php echo $this->__("(GMT-08:00) Pacific Time (US &amp; Canada)"); ?></option>
                    <option value="<?php echo $this->__("(GMT-08:00) Tijuana"); ?>"><?php echo $this->__("(GMT-08:00) Tijuana"); ?></option>
                    <option value="<?php echo $this->__("(GMT-07:00) Arizona"); ?>"><?php echo $this->__("(GMT-07:00) Arizona"); ?></option>
                    <option value="<?php echo $this->__("(GMT-07:00) Chihuahua"); ?>"><?php echo $this->__("(GMT-07:00) Chihuahua"); ?></option>
                    <option value="<?php echo $this->__("(GMT-07:00) Mazatlan "); ?>"><?php echo $this->__("(GMT-07:00) Mazatlan "); ?></option>
                    <option value="<?php echo $this->__("(GMT-07:00) Mountain Time (US &amp; Canada)"); ?>"><?php echo $this->__("(GMT-07:00) Mountain Time (US &amp; Canada)"); ?></option>
                    <option value="<?php echo $this->__("(GMT-06:00) Central America"); ?>"><?php echo $this->__("(GMT-06:00) Central America"); ?></option>
                    <option value="<?php echo $this->__("(GMT-06:00) Central Time (US &amp; Canada)"); ?>"><?php echo $this->__("(GMT-06:00) Central Time (US &amp; Canada)"); ?></option>
                    <option value="<?php echo $this->__("(GMT-06:00) Guadalajara"); ?>"><?php echo $this->__("(GMT-06:00) Guadalajara"); ?></option>
                    <option value="<?php echo $this->__("(GMT-06:00) Mexico City"); ?>"><?php echo $this->__("(GMT-06:00) Mexico City"); ?></option>
                    <option value="<?php echo $this->__("(GMT-06:00) Monterrey") ?>"><?php echo $this->__("(GMT-06:00) Monterrey") ?></option>
                    <option value="<?php echo $this->__("(GMT-06:00) Saskatchewan") ?>"><?php echo $this->__("(GMT-06:00) Saskatchewan") ?></option>
                    <option value="<?php echo $this->__("(GMT-05:00) Bogota") ?>"><?php echo $this->__("(GMT-05:00) Bogota") ?></option>
                    <option value="<?php echo $this->__("(GMT-05:00) Eastern Time (US &amp; Canada)"); ?>"><?php echo $this->__("(GMT-05:00) Eastern Time (US &amp; Canada)"); ?></option>
                    <option value="<?php echo $this->__("(GMT-05:00) Indiana (East)") ?>"><?php echo $this->__("(GMT-05:00) Indiana (East)") ?></option>
                    <option value="<?php echo $this->__("(GMT-05:00) Lima"); ?>"><?php echo $this->__("(GMT-05:00) Lima"); ?></option>
                    <option value="(GMT-05:00) Quito">(GMT-05:00) Quito</option>
                    <option value="(GMT-04:30) Caracas">(GMT-04:30) Caracas</option>
                    <option value="(GMT-04:00) Atlantic Time (Canada)">(GMT-04:00) Atlantic Time (Canada)</option>
                    <option value="(GMT-04:00) Georgetown">(GMT-04:00) Georgetown</option>
                    <option value="(GMT-04:00) La Paz">(GMT-04:00) La Paz</option>
                    <option value="(GMT-04:00) Santiago">(GMT-04:00) Santiago</option>
                    <option value="(GMT-03:30) Newfoundland">(GMT-03:30) Newfoundland</option>
                    <option value="(GMT-03:00) Brasilia">(GMT-03:00) Brasilia</option>
                    <option value="(GMT-03:00) Buenos Aires">(GMT-03:00) Buenos Aires</option>
                    <option value="(GMT-03:00) Greenland">(GMT-03:00) Greenland</option>
                    <option value="(GMT-02:00) Mid-Atlantic">(GMT-02:00) Mid-Atlantic</option>
                    <option value="(GMT-01:00) Azores">(GMT-01:00) Azores</option>
                    <option value="(GMT-01:00) Cape Verde Is.">(GMT-01:00) Cape Verde Is.</option>
                    <option value="(GMT+00:00) Casablanca">(GMT+00:00) Casablanca</option>
                    <option value="(GMT+00:00) Dublin">(GMT+00:00) Dublin</option>
                    <option value="(GMT+00:00) Edinburgh">(GMT+00:00) Edinburgh</option>
                    <option value="(GMT+00:00) Lisbon">(GMT+00:00) Lisbon</option>
                    <option value="(GMT+00:00) London">(GMT+00:00) London</option>
                    <option value="(GMT+00:00) Monrovia">(GMT+00:00) Monrovia</option>
                    <option value="(GMT+00:00) UTC">(GMT+00:00) UTC</option>
                    <option value="(GMT+01:00) Amsterdam">(GMT+01:00) Amsterdam</option>
                    <option value="(GMT+01:00) Belgrade">(GMT+01:00) Belgrade</option>
                    <option value="(GMT+01:00) Berlin">(GMT+01:00) Berlin</option>
                    <option value="(GMT+01:00) Bern">(GMT+01:00) Bern</option>
                    <option value="(GMT+01:00) Bratislava">(GMT+01:00) Bratislava</option>
                    <option value="(GMT+01:00) Brussels">(GMT+01:00) Brussels</option>
                    <option value="(GMT+01:00) Budapest">(GMT+01:00) Budapest</option>
                    <option value="(GMT+01:00) Copenhagen">(GMT+01:00) Copenhagen</option>
                    <option value="(GMT+01:00) Ljubljana">(GMT+01:00) Ljubljana</option>
                    <option value="(GMT+01:00) Madrid">(GMT+01:00) Madrid</option>
                    <option value="(GMT+01:00) Paris">(GMT+01:00) Paris</option>
                    <option value="(GMT+01:00) Prague">(GMT+01:00) Prague</option>
                    <option value="(GMT+01:00) Rome">(GMT+01:00) Rome</option>
                    <option value="(GMT+01:00) Sarajevo">(GMT+01:00) Sarajevo</option>
                    <option value="(GMT+01:00) Skopje">(GMT+01:00) Skopje</option>
                    <option value="(GMT+01:00) Stockholm">(GMT+01:00) Stockholm</option>
                    <option value="(GMT+01:00) Vienna">(GMT+01:00) Vienna</option>
                    <option value="(GMT+01:00) Warsaw">(GMT+01:00) Warsaw</option>
                    <option value="(GMT+01:00) West Central Africa">(GMT+01:00) West Central Africa</option>
                    <option value="(GMT+01:00) Zagreb">(GMT+01:00) Zagreb</option>
                    <option value="(GMT+02:00) Athens">(GMT+02:00) Athens</option>
                    <option value="(GMT+02:00) Bucharest">(GMT+02:00) Bucharest</option>
                    <option value="(GMT+02:00) Cairo">(GMT+02:00) Cairo</option>
                    <option value="(GMT+02:00) Harare">(GMT+02:00) Harare</option>
                    <option value="(GMT+02:00) Helsinki">(GMT+02:00) Helsinki</option>
                    <option value="(GMT+02:00) Istanbul">(GMT+02:00) Istanbul</option>
                    <option value="(GMT+02:00) Jerusalem">(GMT+02:00) Jerusalem</option>
                    <option value="(GMT+02:00) Kyiv">(GMT+02:00) Kyiv</option>
                    <option value="(GMT+02:00) Minsk">(GMT+02:00) Minsk</option>
                    <option value="(GMT+02:00) Pretoria">(GMT+02:00) Pretoria</option>
                    <option value="(GMT+02:00) Riga">(GMT+02:00) Riga</option>
                    <option value="(GMT+02:00) Sofia">(GMT+02:00) Sofia</option>
                    <option value="(GMT+02:00) Tallinn">(GMT+02:00) Tallinn</option>
                    <option value="(GMT+02:00) Vilnius">(GMT+02:00) Vilnius</option>
                    <option value="(GMT+03:00) Baghdad">(GMT+03:00) Baghdad</option>
                    <option value="(GMT+03:00) Kuwait">(GMT+03:00) Kuwait</option>
                    <option value="(GMT+03:00) Nairobi">(GMT+03:00) Nairobi</option>
                    <option value="(GMT+03:00) Riyadh">(GMT+03:00) Riyadh</option>
                    <option value="(GMT+03:30) Tehran">(GMT+03:30) Tehran</option>
                    <option value="(GMT+04:00) Abu Dhabi">(GMT+04:00) Abu Dhabi</option>
                    <option value="(GMT+04:00) Baku">(GMT+04:00) Baku</option>
                    <option value="(GMT+04:00) Moscow">(GMT+04:00) Moscow</option>
                    <option value="(GMT+04:00) Muscat">(GMT+04:00) Muscat</option>
                    <option value="(GMT+04:00) St. Petersburg">(GMT+04:00) St. Petersburg</option>
                    <option value="(GMT+04:00) Tbilisi">(GMT+04:00) Tbilisi</option>
                    <option value="(GMT+04:00) Volgograd">(GMT+04:00) Volgograd</option>
                    <option value="(GMT+04:00) Yerevan">(GMT+04:00) Yerevan</option>
                    <option value="(GMT+04:30) Kabul">(GMT+04:30) Kabul</option>
                    <option value="(GMT+05:00) Islamabad">(GMT+05:00) Islamabad</option>
                    <option value="(GMT+05:00) Karachi">(GMT+05:00) Karachi</option>
                    <option value="(GMT+05:00) Tashkent">(GMT+05:00) Tashkent</option>
                    <option value="(GMT+05:30) Chennai">(GMT+05:30) Chennai</option>
                    <option value="(GMT+05:30) Kolkata">(GMT+05:30) Kolkata</option>
                    <option value="(GMT+05:30) Mumbai">(GMT+05:30) Mumbai</option>
                    <option value="(GMT+05:30) New Delhi">(GMT+05:30) New Delhi</option>
                    <option value="(GMT+05:30) Sri Jayawardenepura">(GMT+05:30) Sri Jayawardenepura</option>
                    <option value="(GMT+05:45) Kathmandu">(GMT+05:45) Kathmandu</option>
                    <option value="(GMT+06:00) Almaty">(GMT+06:00) Almaty</option>
                    <option value="(GMT+06:00) Astana">(GMT+06:00) Astana</option>
                    <option value="(GMT+06:00) Dhaka">(GMT+06:00) Dhaka</option>
                    <option value="(GMT+06:00) Ekaterinburg">(GMT+06:00) Ekaterinburg</option>
                    <option value="(GMT+06:30) Rangoon">(GMT+06:30) Rangoon</option>
                    <option value="(GMT+07:00) Bangkok">(GMT+07:00) Bangkok</option>
                    <option value="(GMT+07:00) Hanoi">(GMT+07:00) Hanoi</option>
                    <option value="(GMT+07:00) Jakarta">(GMT+07:00) Jakarta</option>
                    <option value="(GMT+07:00) Novosibirsk">(GMT+07:00) Novosibirsk</option>
                    <option value="(GMT+08:00) Beijing">(GMT+08:00) Beijing</option>
                    <option value="(GMT+08:00) Chongqing">(GMT+08:00) Chongqing</option>
                    <option value="(GMT+08:00) Hong Kong">(GMT+08:00) Hong Kong</option>
                    <option value="(GMT+08:00) Krasnoyarsk">(GMT+08:00) Krasnoyarsk</option>
                    <option value="(GMT+08:00) Kuala Lumpur">(GMT+08:00) Kuala Lumpur</option>
                    <option value="(GMT+08:00) Perth">(GMT+08:00) Perth</option>
                    <option value="(GMT+08:00) Singapore">(GMT+08:00) Singapore</option>
                    <option value="(GMT+08:00) Taipei">(GMT+08:00) Taipei</option>
                    <option value="(GMT+08:00) Ulaan Bataar">(GMT+08:00) Ulaan Bataar</option>
                    <option value="(GMT+08:00) Urumqi">(GMT+08:00) Urumqi</option>
                    <option value="(GMT+09:00) Irkutsk">(GMT+09:00) Irkutsk</option>
                    <option value="(GMT+09:00) Osaka">(GMT+09:00) Osaka</option>
                    <option value="(GMT+09:00) Sapporo">(GMT+09:00) Sapporo</option>
                    <option value="(GMT+09:00) Seoul">(GMT+09:00) Seoul</option>
                    <option value="(GMT+09:00) Tokyo">(GMT+09:00) Tokyo</option>
                    <option value="(GMT+09:30) Adelaide">(GMT+09:30) Adelaide</option>
                    <option value="(GMT+09:30) Darwin">(GMT+09:30) Darwin</option>
                    <option value="(GMT+10:00) Brisbane">(GMT+10:00) Brisbane</option>
                    <option value="(GMT+10:00) Canberra">(GMT+10:00) Canberra</option>
                    <option value="(GMT+10:00) Guam">(GMT+10:00) Guam</option>
                    <option value="(GMT+10:00) Hobart">(GMT+10:00) Hobart</option>
                    <option value="(GMT+10:00) Melbourne">(GMT+10:00) Melbourne</option>
                    <option value="(GMT+10:00) Port Moresby">(GMT+10:00) Port Moresby</option>
                    <option value="(GMT+10:00) Sydney">(GMT+10:00) Sydney</option>
                    <option value="(GMT+10:00) Yakutsk">(GMT+10:00) Yakutsk</option>
                    <option value="(GMT+11:00) New Caledonia">(GMT+11:00) New Caledonia</option>
                    <option value="(GMT+11:00) Vladivostok">(GMT+11:00) Vladivostok</option>
                    <option value="(GMT+12:00) Auckland">(GMT+12:00) Auckland</option>
                    <option value="(GMT+12:00) Fiji">(GMT+12:00) Fiji</option>
                    <option value="(GMT+12:00) Kamchatka">(GMT+12:00) Kamchatka</option>
                    <option value="(GMT+12:00) Magadan">(GMT+12:00) Magadan</option>
                    <option value="(GMT+12:00) Marshall Is.">(GMT+12:00) Marshall Is.</option>
                    <option value="(GMT+12:00) Solomon Is.">(GMT+12:00) Solomon Is.</option>
                    <option value="(GMT+12:00) Wellington">(GMT+12:00) Wellington</option>
                    <option value="(GMT+13:00) Nuku'alofa">(GMT+13:00) Nuku'alofa</option>
            </select>
        </div>
        <p class="time_zone">
            <?php echo $this->__("Telephone Number") ?>
        </p>
        <div>
            <input type="text" name="mobileNo" id="mobileNo">
        </div>
        <input type="hidden" name="cid" id="cid" value="<?php echo $this->getRequest()->getParam('cid'); ?>" />
        <input type="hidden" name="pid" id="pid" value="<?php echo $this->getRequest()->getParam('pid'); ?>" />
        <div style="margin: 10px 0px 15px 10px">
        <input type="submit" class="button-glossy blue"  value="<?php echo $this->__("Send Message") ?>" style="width: 180px" onclick="return validateForm();"/>
        </div>
    </form>
