<link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'/>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
<script type="text/javascript">
    function initialize() {
        var mapOptions = {
            //center: new google.maps.LatLng(-33.8688, 151.2195),
            zoom: 13,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById('map_canvas'),
        mapOptions);

        var input = document.getElementById('searchTextField');
        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.bindTo('bounds', map);
        // Autocomplete.
        function setupClickListener(id, types) {
            var radioButton = document.getElementById(id);
            google.maps.event.addDomListener(radioButton, 'click', function() {
                autocomplete.setTypes(types);
            });
        }

    }
    google.maps.event.addDomListener(window, 'load', initialize); 
    
    function initialize2() {
        var mapOptions = {
            //center: new google.maps.LatLng(-33.8688, 151.2195),
            zoom: 13,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById('map_canvas2'),
        mapOptions);

        var input = document.getElementById('bestDealcity');
        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.bindTo('region', map);
        // Autocomplete.
        function setupClickListener(id, types) {
            var radioButton = document.getElementById(id);
            google.maps.event.addDomListener(radioButton, 'click', function() {
                autocomplete.setTypes(types);
            });
        }

    }
    google.maps.event.addDomListener(window, 'load', initialize2);
</script>

<?php
$count = 1;
$threeDiv = 1;
$model = Mage::getModel('catalog/product');
$baseurl = Mage::getBaseUrl('skin');


$_productCollection = Mage::getModel('airhotels/property')->getpropertycollection()
                ->addAttributeToFilter('status', array('eq' => 1))
                ->setPageSize(10)->setOrder('created_at', 'desc')->addAttributeToSelect('*');
$currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
//if(count($_productCollection)!= 0){

?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('jcarousel/jquery.jcarousel.min.js')?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('jcarousel/skin.css')?>" />
<script type="text/javascript">
function mycarousel_initCallback(carousel)
{
    // Disable autoscrolling if the user clicks the prev or next button.
    carousel.buttonNext.bind('click', function() {
        carousel.startAuto(0);
    });

    carousel.buttonPrev.bind('click', function() {
        carousel.startAuto(0);
    });

    // Pause autoscrolling if the user moves with the cursor over the clip.
    carousel.clip.hover(function() {
        carousel.stopAuto();
    }, function() {
        carousel.startAuto();
    });
};

jQuery(document).ready(function() {	
	jQuery('#menuwhatnew').jcarousel();
});

</script>



<!-- Scroll most rated js -->

  <!--<script type="text/javascript" src="http://www.dev.restostay.com/js/scroll/jquery-1.3.2.min.js"></script> 
  <script type="text/javascript" src="http://www.dev.restostay.com/js/scroll/jcarousellite_1.0.1.pack.js"></script> 
 	
      <script type="text/javascript">
		 
		jQuery(function() {
			
    		jQuery(".slider").jCarouselLite({
        		
        		//btnPrev: ".prev",
				//btnPrev1: ".prev",
				visible: 4
    		});
		});
		
		
	</script>-->
    <!-- Scroll image -->
   <!-- <link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"> -->
    <link href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>js/scroll/bootstrap.min.css" rel="stylesheet">
   
   <style>
	

h1, h2 {
  padding-top: 20px;
}
.scroll-text {
  border: 1px solid #9c1e1f;
  width: 400px;
  height: 4.5em;
  overflow: hidden;
}
.scroll-text ul {
  width: 800px;
  height: 100px;
  overflow: hidden;
  margin: 0;
}
.scroll-text ul li {
  height: 1.5em;
}
.scroll-img {
  border: 1px solid #9c1e1f;
  width: 998px;
  height: 160px;
  overflow: hidden;
  font-size: 0;
}
.scroll-img ul {
  width: 700px;
  height: 600px;
  margin: 0;
}
.scroll-img ul li {
  display: inline-block;
  margin: 10px 0 10px 10px;
}
#demo4.scroll-img ul,
#demo5.scroll-img ul {
  width: 1500px;
}
#demo5-btn {
  width: 680px;
  padding-top: 10px;
}



    </style>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>js/scroll/jquery.scrollbox.js"></script>
    <script>
		jQuery(function () {
		 
		 jQuery('.demo5').scrollbox({
			direction: 'h',
			distance: 134
		  });
		});
</script>
    <!-- End -->
  
    
    
<!-- end -->
<div class="clear"></div>
<div id="roomshomepage">
    <div id="room" class="clearfix">
        <div id="left_columnhomepage">
            <div id="main_content" class="box">
                <div class="tabhomepage" style="position: relative; display: block;">
                    
                    <ul id="main_content_sub_navhomepage" class="rooms_sub_navhomepage clearfix ">
                        <li id="menuPopular" class="main_link selected">
                            <a href="#mostrated" onclick="showTabs('popular_div','menuPopular')"><?php echo $this->__('Most Popular'); ?></a>
                        </li>
                        <li id="menuDeal" class="main_link">
                            <a href="#bestdeal" onclick="showTabs('deal_div','menuDeal')"><?php echo $this->__('Best Deal'); ?></a>
                        </li>
                        <li id="menuwhatnew" class="main_link">
                            <a href="#whatnew" onclick="showTabs('whatsnew','menuwhatnew')"><?php echo $this->__('What\'s New'); ?></a>
                        </li>    
<!--                        <li id="content_flag">
                            
                        </li>-->
                    </ul>
                   
                    <div id="whatsnew" class="main_content" style="display: block; ">
                    
                   <!--  <div class="prev"><img onclick="return wn(leftname.value)" src="images/prev.jpg" alt="prev" /></div> -->
                    <!-- <div class="slider"> -->
                    <div id="demo5" class="scroll-img demo5">
                       <!-- <marquee onmouseover="this.stop();" onmouseout="this.start();" loop="repeat"> -->
                        <ul id="homepage_badges" style="display: block;<?php if(count($_productCollection)== 0 ) echo "text-align: center;" ?> ">
                        
                            <?php
                           if(count($_productCollection)!= 0 ){
                            $count = 1;
                            foreach ($_productCollection as $_product):
                                if ($count <= 5):
                                    ?>
                         
                            <?php
							$productId = $_product->getId();
							$model = Mage::getModel('catalog/product'); //getting product model
                            $product = $model->load($productId);
                            $mainimage=$this->helper('catalog/image')->init($product, 'image')
							 ->constrainOnly(TRUE)
                                ->keepAspectRatio(TRUE)
                                ->keepFrame(FALSE)
							->resize(200,null);
                            ?>
                           
                                    <li class="rounded" <?php if($count == 4) { echo 'style=" margin-right:0;" ' ;}?>>
                                        <a class="ss_name" href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>"  >
                                            <img src="<?php
                            if ($product->getImage() != 'no_selection') {
                                echo $mainimage;
                            } else { 
                                echo $product->getImageUrl();
                            }
                                    ?>" width="230" height="140" title="<?php echo substr($product->getName(), 0, 25); ?>" class="captify" >
                                        </a>
                                        <div class="box-shadow">
                                             <a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>" style="text-decoration: none;">
                                            <?php echo substr($product->getName(), 0, 30); ?>
											
                                             </a>
                                        </div>
                                    </li>
                                    
                                    <?php
                                endif;
                                $count++;
                            endforeach;
                           }else{
                               echo $this->__('No Records!');

                           }
                            ?>
                            
                           
                        </ul>
                        <!-- </marquee> -->
                        </div>
                        <!-- <div class="next"><img id="homepage_badges1" src="images/next.jpg" alt="next" onclick="return test(count.value)"  /> </div> -->
                        
                    </div>
                    <!-- best deal -->
                    <?php $bestDealCategory=Mage::Helper('airhotels/property')->getBestDealCategory(); ?>
                    <?php $bestDealCollection = Mage::getModel('catalog/category')->load($bestDealCategory)->getProductCollection()->addAttributeToSelect('*')->setOrder('cat_index_position', 'DESC'); ?>
                    <div id="deal_div" class="main_content" style="display: none;">
                        <div class="search-area" style=" left: 374px; top: 0px; padding-top: 0px; ">
                            <img id="bestDealcityloading" style="display: none" alt="loading" src="<?php echo $this->getSkinUrl('/images/loader.gif')?>">
                                <input id="bestDealcity" name="bestDealcity" type="text" class="searchmainpage"  placeholder="Search Best Deal In City" onfocus="if (this.placeholder == 'Search Best Deal In City') {this.placeholder = '';this.style.color ='#333333';}" onblur="if (this.placeholder == '') {this.style.color ='#333333';this.placeholder = 'Search Best Deal In City';} "style="padding: 5px"/> 
                                <div id="search_options" class=" left" style=""></div>
                                <button  onclick="bestDealcitySearch()" type="submit" class="large pink btn icon-only" style="width: 45px !important;padding: 0px;height: 28px;margin-left: 10px;" /> 
                                <div id="map_canvas2" style="width:427px;"></div>
                        </div>
                        <div id="demo5" class="scroll-img demo5">
                            <ul id="rated_badges" style="display: block; <?php if (count($bestDealCollection) == 0) echo "text-align: center;" ?>">
                                <?php if (count($bestDealCollection) !=0) { ?>
                                    <?php $countBestDeal = 1; ?>
                                    <?php foreach ($bestDealCollection as $bestDealProduct) { ?>
                                        <?php $_product12 = Mage::getModel('catalog/product')->load($bestDealProduct->getId()); ?>
                                        <?php $rateimage = $this->helper('catalog/image')->init($_product12, 'image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(200, null); ?>
                                        <li class="rounded rated" <?php if ($countBestDeal == 4) {
                                    echo 'style=" margin-right:0;" ';
                                } ?>>
                                            <a class="ss_name" href="<?php echo Mage::getBaseUrl() . $bestDealProduct->getUrlPath(); ?>">
                                                <img alt="" src="<?php
                                                if ($bestDealProduct->getImage() != 'no_selection') {
                                                    echo $rateimage;
                                                } else {
                                                    echo $_product12->getImageUrl();
                                                }
                                                ?>" width="230" height="140" title="<?php echo substr($bestDealProduct->getName(), 0, 25); ?>" class="captify">
                                            </a>
                                            <div class="box-shadow">
                                                <a href="<?php echo Mage::getBaseUrl() . $bestDealProduct->getUrlPath(); ?>" style="text-decoration: none;">
                                                    <?php echo substr($bestDealProduct->getName(), 0, 30); ?>
                                                </a>
                                            </div>
                                        </li>
                                        <?php
                                        $countBestDeal++;
                                    }
                                } else {
                                    echo $this->__('No Records!');
                                }
                                ?>
                            </ul>
                            <!-- </marquee> -->
                        </div>

                    </div>
                    <!-- best deal ends -->
                    <!-- most popular -->
                    <?php $mostPopularCategory=Mage::Helper('airhotels/property')->getMostPopularCategory(); ?>
                    <?php $mostPopularCollection = Mage::getModel('catalog/category')->load($mostPopularCategory)->getProductCollection()->addAttributeToSelect('*')->setOrder('cat_index_position', 'DESC'); ?>
                    <div id="popular_div" class="main_content" style="display: none;">
                         

                        <!-- <div class="slider" id="slider2"> -->
                        <div id="demo5" class="scroll-img demo5">
                            <!-- <marquee onmouseover="this.stop();" onmouseout="this.start();" loop="repeat" width="100%" behavior="scroll"> -->

                            <ul id="popular_badges" style="padding:0;" class="popular_badges1">
                                <?php if (count($mostPopularCollection) != 0) {
                                    $countPopular = 1; ?>
                                    <?php foreach ($mostPopularCollection as $_mostPopularProduct) { ?>
                                            <?php $mostPopularProduct = $model->load($_mostPopularProduct->getId()); ?>
                                            <li class="rounded round" <?php if ($countPopular == 4) { ?>
                                                <?php echo 'style=" margin-right:0;" '; } ?>>
                                            <a class="ss_name" href="<?php echo Mage::getBaseUrl() . $mostPopularProduct->getUrlPath(); ?>">
                                                <img alt="" src="<?php
                                                if ($mostPopularProduct->getImage() != "no_selection") {
                                                    echo Mage::getBaseUrl('media') . 'catalog/product/' . $mostPopularProduct->getImage();
                                                } else {
                                                    echo $mostPopularProduct->getImageUrl();
                                                }
                                                ?>" width="230" height="140" title="<?php echo substr($mostPopularProduct->getName(), 0, 25); ?>">
                                            </a>
                                            <div class="box-shadow">
                                                <a href="<?php echo Mage::getBaseUrl() . $mostPopularProduct->getUrlPath(); ?>" style="text-decoration: none;">
                                        <?php echo substr($mostPopularProduct->getName(), 0, 30); ?>
                                                </a>
                                            </div>
                                        </li>
                                        <?php
                                        $countPopular++;
                                    }
                                } else {
                                    echo $this->__('No Records!');

                                }
                                ?>
                            </ul>

                            <!-- </marquee> -->
                        </div>
                       <!-- <div class="next"><img onclick="return most(count.value)" src="images/next.jpg" alt="next" /> </div> -->

                    </div>
                    <!-- most popular -->
                        
                        
                </div>
                    
                    
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var $slide = jQuery.noConflict();
    function bestDealcitySearch(){    
                  var bestDealcity=document.getElementById("bestDealcity").value;  
                    if(bestDealcity==""){
				alert("Please enter a city name");
				document.getElementById("bestDealcity").focus();
				return false;
		    }
            jQuery("#bestDealcityloading").show();
            jQuery.ajax({
                url: "<?php echo $this->getUrl('airhotels/property/ajaxBestDeal'); ?>",
                context: document.body,
                data: {city:bestDealcity},
                success: function(data){
                    jQuery("#rated_badges").text=data;
                    document.getElementById("rated_badges").innerHTML=   data;
                    jQuery("#bestDealcityloading").hide();        
                }
            });    
    }
    
    function showTabs(id,menuName){ 
        $slide(".main_content").hide();
        $slide(".main_link").removeClass("selected");
        $slide("#"+menuName).addClass("selected");
        $slide("#"+id).show();
		
		document.getElementById("leftname").value="";
		document.getElementById("count").value=1;
		
		
		jQuery("#slider1").removeAttr('style');
		jQuery('#slider1').attr('style', 'width: 980px !important; left: 0; overflow: hidden; position: relative; visibility: visible; z-index: 2');
		
		
		jQuery('.rated').attr('style', 'width: 230px !important; height: 140px; float: left; overflow: hidden;');
    	
		//jQuery("#rated_badges").removeAttr('style');
		
		
		
		
		jQuery("#slider2").removeAttr('style');
		jQuery('#slider2').attr('style', 'width: 980px !important; left: 0; overflow: hidden; position: relative; visibility: visible; z-index: 2');
		jQuery('.round').attr('style', 'width: 230px !important; height: 140px; float: left; overflow: hidden;');
		
	
    }
	
	
	
	
	
	
	
	/*function abc(count){
		
    	if (count > 1) {
			var v = document.getElementById("leftname").value;
			 var nv = parseInt(v)+parseInt(178);
			jQuery("#rated_badges").attr('style','width:3185px; left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
			
			document.getElementById("leftname").value= nv;
			
			
     
    	}
		else
		{
		jQuery("#rated_badges").attr('style', 'width:3185px; left:-250px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= 250;
	
		}
		count++;
		document.getElementById("count").value=count;
			
	}
	
	function test(count){
		
    	if (count > 1) {
			var v = document.getElementById("leftname").value;
			 var nv = parseInt(v)+parseInt(178);
			jQuery("#homepage_badges").attr('style','width:3185px; left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
			document.getElementById("leftname").value= nv;
			
			
      
    	}
		else
		{
		jQuery("#homepage_badges").attr('style', 'width:3185px; left:-250px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= 250;
	
		}
		count++;
		document.getElementById("count").value=count;
  		
		
				
		
	}
	
	function most(count){
		
    	if (count > 1) {
			var v = document.getElementById("leftname").value;
			 var nv = parseInt(v)+parseInt(178);
			 
			jQuery("#popular_badges").attr('style','width:3185px; left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
			document.getElementById("leftname").value= nv;
     
    	}
		else
		{
		jQuery("#popular_badges").attr('style', 'width:3185px; left:-250px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= 250;
	
		}
		count++;
		document.getElementById("count").value=count;
  		
		
	}
	
	
	
	function mrated(){
		
		var v = document.getElementById("leftname").value;
		var nv = parseInt(v)-parseInt(178);
		
		jQuery("#rated_badges").attr('style','width:3185px; left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= nv;
			
	}
	
	
	function wn(){
		//alert("test");
		var v = document.getElementById("leftname").value;
		var nv = parseInt(v)-parseInt(178);
		//alert(nv);
		jQuery("#homepage_badges").attr('style','width:3185px; left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= nv;
			
	}
	
	function mp(){
		//alert("test");
		var v = document.getElementById("leftname").value;
		var nv = parseInt(v)-parseInt(178);
		//alert(nv);
		jQuery("#popular_badges").attr('style','width:3185px; left:-'+nv+'px; list-style-type:none; margin:0; padding:0; position:relative; z-index:1;');
		document.getElementById("leftname").value= nv;
			
	}
	
	
	jQuery(document).ready(function(){
		
		jQuery("#homepage_badges").removeAttr('style');	
		jQuery(".slider").removeAttr('style');
		jQuery('.slider').attr('style', 'width: 3250 !important; left: 0; overflow: hidden; position: relative; visibility: visible; z-index: 2');
	});*/
</script>

<input type="hidden" name="leftname" id="leftname" value=""  />
<input type="hidden" name="count" id="count" value="1"  />
<input type="hidden" name="previ" id="previ" value=""  />