<?php
/**
 * @name         :  Apptha One Step Checkout
 * @version      :  1.4
 * @since        :  Magento 1.4
 * @author       :  Apptha - http://www.apptha.com
 * @copyright    :  Copyright (C) 2011 Powered by Apptha
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  June 20 2011
 * 
 * */
?>

<?php
/**
 * One page checkout payment methods
 *
 * @see Mage_Checkout_Block_Onepage_Payment_Methods
 */
?>
<?php 
$paymentmethods = Mage::getStoreConfig('onestepcheckout/general/default_payment_method');
$api = $this->helper('onestepcheckout')->license();
if($api): ?>
<dl class="sp-methods" id="checkout-payment-method-load">
<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
    <dt>
    <?php if( sizeof($this->getMethods()) > 1 ): ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code || $_code==$paymentmethods): ?> checked="checked"<?php endif; ?>  class="radio validate-one-required-by-name" />
    <?php else: ?>
        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($_code): ?> checked="checked"<?php endif; ?>  class="radio" /></span>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
    </dt>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
    <dd id="container_payment_method_<?php echo $_code; ?>" class="payment-method">
        <?php echo $html; ?>
    </dd>
    <?php endif; ?>
<?php endforeach; ?>
</dl>
<?php echo $this->getChildChildHtml('additional'); ?>
<?php endif;?>

<script type="text/javascript">
var paymentMethod;
//<![CDATA[
<?php  if(sizeof($this->getMethods()) ==1 || isset($paymentmethods)) { ?>
paymentMethod = "<?php echo $paymentmethods ?>"; 

<?php }?>    
//]]> 
 
window.onload = function() {
//<![CDATA[
<?php  if(sizeof($this->getMethods()) ==1 || isset($paymentmethods)) { ?>
payment.currentMethod = "<?php echo $paymentmethods ?>"; 
payment.switchMethod('<?php echo $paymentmethods ?>') <?php }?>    
<?php echo $this->getChildChildHtml('scripts'); ?>
//payment.init();
//]]> 
 
}

//var checkout = new Checkout();
$$('#checkout-payment-method-load dt input').invoke('observe', 'click', function(e) {

    var element = e.element();
    var name = 'payment_form_' + element.getValue();
    payment.currentMethod = element.getValue();
    /* Hide all other forms */
    $$('dd.payment-method').invoke('hide');

    if(element.checked) {
        var form = $(name);
        var container = $('container_payment_method_' + element.getValue());

        if(element !== null && container !== null)    {
            container.show();
            $(name).show();
        }
    }
});
</script>